apiVersion: v1
baseDomain: okd4.local
metadata:
  name: okd # cluster name
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDadexClK8TQ3Z5sU0ZVY+F/mrrWz//zOvwtXTOEs4X8mDQAIdBRaun+u1+abfJgqzD58ZIdEs2zbAmdzGtEPTJJSRrGXmvFqpfmbsetPClUe/QJ0KxLRHyPnYOgIFxo3S4lqZW71/K7eAKoeMyOpKZ7+6yRsFyzyrPpt4ue7uDFMOCVC1yDrQRRKktP4tf2wnhBSn0xP1YKbShkNPJ7/MbHpjb8Bpoo7oPje4wCBn/IZccuXVoTB7CkNckc/8OcGrgu1eW8wd9YvkuxJ6CJacxxA28p2HIotU7I0B6fjKz+hhTavngpYzDyEucVS21sMvyqupZ5aI4aBehUvfZl+pbF60wMUFT1DwKhBJC3CmaGs8LSR3Dgo23511odqJ4GkMks6VK3CdBP0i+OMlQzwnHKjhKTe/em/bLuY6jhjAnm1zdBIT51/q3ueAm1DW67nIxIQTQYVPXvOhXvFriO/UfYGD1mZd3j8L/fU5toUKtIFjcSThV/LAKNskPyP0E2h0= sysadmin@okd4-svc.okd.okd4.local'
